version: "3.1"

# Replace secret_key:
# :redir @* | !openssl rand -base64 32 | tr -d '\n' | xclip -selection clipboard
# 11,$s/SECRET_KEY=""/SECRET_KEY=""
# 11,$s/SECRET_KEY="*.*"/SECRET_KEY=""
#
# Replace all the database credentials
# 9s/entity/webapp/g
# 11,$s/base:base@database\/base/webapp:webapp@database\/webapp/g
#
# Script to seed the database

services:
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: webapp
    command: [ "docker-entrypoint.sh", "-c", "wal_level=logical", "-c", "max_connections=300" ]

# {{{ fcm
  fcm_api:
    image: kennycallado/q-api-fcm:latest
    ports:
      - "8005:8000"
    expose:
      - "8005:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
    depends_on:
      - database
# }}}

# {{{ profiles - users - auth
  # {{{ profiles
  profiles_api:
    image: kennycallado/q-api-profiles:latest
    ports:
      - "8001:8000"
    expose:
      - "8001:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
    depends_on:
      - database
  # }}}

  # {{{ users
  users_api:
    image: kennycallado/q-api-users:latest
    ports:
      - "8002:8000"
    expose:
      - "8002:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/user"
      - ROCKET_FCM_URL="http://fcm_api:8000/api/v1/fcm/"
    depends_on:
      - database
  # }}}

  # {{{ auth
  auth_api:
    image: kennycallado/q-api-auth:latest
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - "8003:8000"
    expose:
      - "8003:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
    depends_on:
      - users_api
  # }}}
# }}}

# {{{ questions - answers
  # {{{ questions
  questions_api:
    image: kennycallado/q-api-questions:latest
    ports:
      - "8011:8000"
    expose:
      - "8011:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
    depends_on:
      - users_api
  # }}}

  # {{{ answers
  answers_api:
    image: kennycallado/q-api-answers:latest
    ports:
      - "8012:8000"
    expose:
      - "8012:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
    depends_on:
      - questions_api
  # }}}
# }}}

# {{{ slides
  # {{{ slides
  slides_api:
    image: kennycallado/q-api-slides:latest
    ports:
      - "8021:8000"
    expose:
      - "8021:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question"
    depends_on:
      - questions_api
  # }}}
# }}}

# {{{ resources - papers
  # {{{ resources
  resources_api:
    image: kennycallado/q-api-resources:latest
    ports:
      - "8031:8000"
    expose:
      - "8031:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
    depends_on:
      - slides_api
  # }}}

  # {{{ papers
  papers_api:
    image: kennycallado/q-api-papers:latest
    ports:
      - "8032:8000"
    expose:
      - "8032:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
    depends_on:
      - resources_api
  # }}}
# }}}

# {{{ checker - logics
  # {{{ checker
  checker_api:
    image: kennycallado/q-api-checker:latest
    ports:
      - "3000:3000"
    expose:
      - "3000:3000"
  # }}}

  # {{{ logics
  logics_api:
    image: kennycallado/q-api-logics:latest
    ports:
      - "8041:8000"
    expose:
      - "8041:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
      - ROCKET_CHECKER_URL="http://checker_api:3000/"
    depends_on:
      - checker_api
      - projects_api
      - users_api
  # }}}
# }}}

# {{{ projects
  projects_api:
    image: kennycallado/q-api-projects:latest
    ports:
      - "8051:8000"
    expose:
      - "8051:8000"
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://webapp:webapp@database/webapp"}}
    depends_on:
      - database
# }}}
